FROM nomuna/centos6_libc2.12:latest
MAINTAINER nbatsukh "batsukh@appplant.de"

ENV APP_HOME /code
WORKDIR $APP_HOME

ENV ORBIT_KEY="/.ssh/orbit.key" ORBIT_HOME="/code/bintest/testFolder"

COPY scripts/docker/centos/install_centos6.sh install.sh

RUN sh install.sh

RUN go get gopkg.in/hypersleep/easyssh.v0
RUN go get github.com/Sirupsen/logrus

RUN git -C $GOPATH/src/golang.org/x/crypto reset --hard abc5fa7ad02123a41f02bf1391c9760f7586e608
