#!/bin/bash

if [ "$1" == "-t" ]
  then
  if [ "$2" == "app" ] || [ "$2" == "unauthorized" ] || [ "$2" == "offline" ]
    then
    echo server
    exit 0
  fi
  if [ "$2" == "db" ]
    then
    echo db
    exit 0
  fi
  if [ "$2" == "web" ]
    then
    echo web
    exit 0
  fi
fi
ERRORED="false"
if [ "$1" == "-f=ski" ]
  then
  if [ "$2" == "app" ]
    then
    echo "1|app|server|App-Package 1|"`whoami`"@localhost"

  fi
  if  [ "$2" == "web" ]
    then
    echo "1|web|web|App-Package 1|"`whoami`"@localhost"

  fi
  if  [ "$2" == "db" ]
    then
    echo "1|db|db|App-Package 1|dbdb:"`whoami`"@localhost"

  fi
  if [ "$2" == "unauthorized" ]
    then
    echo "0|unknown|unknown|unknown|unknown"
    ERRORED="true"
  fi
  if [ "$2" == "offline" ]
    then
    echo "0|unknown|unknown|unknown|unknown"
    ERRORED="true"
  fi
  if [ "$3" == "app" ]
    then
    echo "1|app|server|App-Package 1|"`whoami`"@localhost"

  fi
  if  [ "$3" == "web" ]
    then
    echo "1|web|web|App-Package 1|"`whoami`"@localhost"

  fi
  if  [ "$3" == "db" ]
    then
    echo "1|db|db|App-Package 1|dbdb:"`whoami`"@localhost"

  fi
  if [ "$3" == "unauthorized" ]
    then
    echo "0|unknown|unknown|unknown|unknown"
    ERRORED="true"
  fi
  if [ "$3" == "offline" ]
    then
    echo "0|unknown|unknown|unknown|unknown"
    ERRORED="true"
  fi
  if [ "$4" == "app" ]
    then
    echo "1|app|server|App-Package 1|"`whoami`"@localhost"

  fi
  if  [ "$4" == "web" ]
    then
    echo "1|web|web|App-Package 1|"`whoami`"@localhost"

  fi
  if  [ "$4" == "db" ]
    then
    echo "1|db|db|App-Package 1|dbdb:"`whoami`"@localhost"

  fi
  if [ "$4" == "unauthorized" ]
    then
    echo "0|unknown|unknown|unknown|unknown"
    ERRORED="true"
  fi
  if [ "$4" == "offline" ]
    then
    echo "0|unknown|unknown|unknown|unknown"
    ERRORED="true"
  fi
  if [ "$5" == "app" ]
    then
    echo "1|app|server|App-Package 1|"`whoami`"@localhost"

  fi
  if  [ "$5" == "web" ]
    then
    echo "1|web|web|App-Package 1|"`whoami`"@localhost"

  fi
  if  [ "$5" == "db" ]
    then
    echo "1|db|db|App-Package 1|dbdb:"`whoami`"@localhost"

  fi
  if [ "$5" == "unauthorized" ]
    then
    echo "0|unknown|unknown|unknown|unknown"
    ERRORED="true"
  fi
  if [ "$5" == "offline" ]
    then
    echo "0|unknown|unknown|unknown|unknown"
    ERRORED="true"
  fi
fi
if [ $ERRORED == "true" ]
  then exit 1
fi
