#!/bin/bash

if [ "$1" == "-t" ]
  then
  if [ "$2" == "app" ] || [ "$2" == "unauthorized" ] || [ "$2" == "offline" ]
    then
    echo server
    exit 0
  fi
  if [ "$2" == "db" ]
    then
    echo db
    exit 0
  fi
  if [ "$2" == "web" ]
    then
    echo web
    exit 0
  fi
fi

if [ "$1" == "-f=ski" ]
  then
  if [ "$2" == "app" ]
    then
    echo "app|server|App-Package 1|"`whoami`"@localhost"
    exit 0
  fi
  if  [ "$2" == "web" ]
    then
    echo "web|web|App-Package 1|"`whoami`"@localhost"
    exit 0
  fi
  if  [ "$2" == "db" ]
    then
    echo "db|db|App-Package 1|dbdb:"`whoami`"@localhost"
    exit 0
  fi
  if [ "$2" == "unauthorized" ]
    then
    echo "unknown|unknown|unknown|unknown"
    exit 1
  fi
  if [ "$2" == "offline" ]
    then
    echo "unknown|unknown|unknown|unknown"
    exit 1
  fi
fi
echo "unknown|unknown|unknown|unknown"
exit 1
