#!/bin/sh

if [ "$1" == "-t" ]
  then
  if [ "$2" == "id1" ]
  	then
  	echo "server"
  fi
  if [ "$2" == "id3" ]
  	then
  	echo "db"
  fi
  if [ "$2" == "id5" ]
  	then
  	echo "web"
  fi
fi
if [ "$1" == "id1" ]
	then
	echo "user1@url1.de"
fi
