package main

const templateDirectory = "templates"
const scriptDirectory = "scripts"
const configDirectory = "config"
const sqlDirectory = "sql"
const pyScriptPath = "pythonScripts"
const thirdPartySoftwareDirectory = "vendor"
const textFSMDirectory = "textfsm"
const textFSMName = "textfsm.py"
const database = "db"
const linuxServer = "server"
const webServer = "web"
const pythonScriptName = "textfsm.py"
const tmpTableFileName = "orbitTable.txt"
const skiDelim = "|"
const tableDelim = "|"
