package main

const templateDirectory = "templates"
const scriptDirectory = "scripts"
const sqlDirectory = "sql"
const configDirectory = "config"
const pyScriptPath = "pythonScripts"
const thirdPartySoftwareDirectory = "vendor"
const textFSMDirectory = "textfsm"
const textFSMName = "textfsm.py"
const database = "db"
const linuxServer = "server"
const webServer = "web"
const pythonScriptName = "textfsm.py"
const tmpTableFileName = "orbitTable"
const skiDelim = "|"
const tableDelim = "|"
const windows = "windows"
const linux = "linux"
const mac = "darwin"
const dbCommand = ". profiles/%s.prof && pqdb_sql.out -x -s %s ~/sql/%s"
const fifaTokenCount = 5
